### ISSUE TITLE
X-Path query example

### ISSUE THREAD

**Issue by madejejej** [r3ggi/SKF-Ruby-Code-Examples#1]
I can't reproduce this one. Does it suggest to use a custom `Encoder` class or are you using an existing implementation?

**Comment by r3ggi** [comment]
The Encoder class is from https://github.com/r3ggi/SKF-Ruby-Code-Examples/blob/master/code-examples/Encoder.rb

**Comment by madejejej** [comment]
@r3ggi makes sense. However, the Encoder class looks a bit too simple for a real-world scenario:

```ruby
class Encoder
  # Application has to protect itself. Every bad input the counter will increment. If the counter
  # hits 3 user's session must be terminated.
  attr_reader :counter

  def initialize
    @counter = 0
  end

  def encoder(input, allowed_characters)
    pattern = "^[a-zA-Z0-9#{allowed_characters}]+$"
    regex = Regexp.compile(pattern)

    unless input =~ regex
      @counter += 1

      # Every bad input validation has to be logged.
      Rails.logger.warn "#{session.id} -> Bad user input"

      if @counter >= 3
        # DO LOGOUT HERE
      end

      return false
    end

    sanitize(input)
  end
end
```

It's hard to maintain the lifecycle of this object for a specific user (especially in a distributed environment). Also two other things came to my mind:

1. Should we reset the counter once the user stops being evil?
2. Should there be a TTL?

You'd probably want to store the `counter` on a per-user basis in a cache/key-value store like Redis. Here's a quick draft of what I mean:

```ruby
class Encoder
  # include SanitizeHelper for the implementation of #sanitize method
  include ActionView::Helpers::SanitizeHelper

  attr_reader :store

  # if your app is hosted on more than one server you should use a key-value store
  # for the Rails.cache backend
  def initialize(store = Rails.cache)
    @store = store
  end

  def encoder(user, input, allowed_characters)
    pattern = "^[a-zA-Z0-9#{allowed_characters}]+$"
    regex = Regexp.compile(pattern)

    unless input =~ regex
      cache_key = cache_key(user)
      store.increment(cache_key)

      # Every bad input validation has to be logged.
      Rails.logger.warn "#{session.id} -> Bad user input"

      if store.fetch(cache_key) >= 3
        # DO LOGOUT HERE
        store.delete(cache_key)
      end

      return false
    end

    sanitize(input)
  end

  private

  def cache_key(user)
    "#{user.cache_key}/input_counter"
  end
end
```

**Comment by r3ggi** [comment]
I wanted the counter to be destroyed with the whole Encoder's object when user is being logged out. Idea with the storage is excellent though, so please do a pull request.

The point of writing this code example was only to share the idea how Encoder should look (it has do ofc check the input with the patter, but also log out suspicious users and put down that action to Rails' logs).

PHP encoder class can be found here:
https://github.com/blabla1337/skf-flask/blob/master/skf/markdown/code_examples/php/43-code_example--Encoder--.md
