### ISSUE TITLE
Pragma: no-cache

### ISSUE THREAD

**Issue by madejejej** [r3ggi/SKF-Ruby-Code-Examples#4]
I got interested in what's going on in the configuration and I also stumbled upon a StackOverflow question about the difference between `Pragma: no-cache` and `Cache-Control: no-cache`.

Cache-Control got introduced in HTTP 1.1 so that's obviously a problem. But it looks like the HTTP spec defines `Pragma: no-cache` only in the request part. It doesn't specify what should happen if you add this header in the response. (https://stackoverflow.com/questions/10314174/difference-between-pragma-and-cache-control-headers)

Should:

```ruby
config.action_controller.perform_caching = false
config.public_file_server.headers = {
  'Pragma' => 'no-cache' # HTTP 1.0
}
```

be changed to:

```ruby
config.action_controller.perform_caching = false
config.public_file_server.headers = {
  'Cache-Control' => 'no-cache'
}
```

**Comment by madejejej** [comment]
Also these two settings make sure that the caching logic on the ActionController level is disabled but the Pragma header only gets attached to assets and static files. You should probably do something like this to make sure every response has no-cache header:

```ruby
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_no_cache_headers

  def set_no_cache_headers
    headers['Pragma'] = 'no-cache'
  end
end
```

or on the configuration level:

```ruby
# config/environments/production.rb
config.action_dispatch.default_headers = {  'Pragma' => 'no-cache' } 
```

**Comment by r3ggi** [comment]
Fixed - Thank you
