### ISSUE TITLE
Audit Logs is not 100% done?

### ISSUE THREAD

**Issue by madejejej** [r3ggi/SKF-Ruby-Code-Examples#8]
I looked into the PHP examples on SKF https://demo.securityknowledgeframework.org/code-examples and it looks like the Audit Logs example isn't fully ported. Although Rails logs all requests I'm not sure it logs user ids when using Devise. Also it looks like the PHP example is focused only on logging possible threats into a separate file + it introduces a DB table for keeping the per-user threat counts. This is what I proposed in https://github.com/r3ggi/SKF-Ruby-Code-Examples/issues/1 (although I suggested Redis instead).

**Comment by r3ggi** [comment]
Hey!
PHP example introduces new table because it's written in pure PHP without using any framework.

The implementation of Encoder class covers logging potential threats. The Redis solution is also nice, so you can do a pull request ;-)
